"""W14 — Collaborative Group Trips."""

from __future__ import annotations

from datetime import UTC, datetime

from fastapi import APIRouter, Body, Query
from pydantic import BaseModel

from app.middleware.error_handler import NotFoundError
from app.models.documents import CollaboratorRole, TripCollaborator, TripDocument
from app.services.trip_service import TripService

router = APIRouter(prefix="/api", tags=["collaborate"])


# ── Permission helpers ───────────────────────────────────────────────


def _is_owner(trip: TripDocument, user_id: str) -> bool:
    return trip.user_id == user_id


def _get_collab(trip: TripDocument, user_id: str) -> TripCollaborator | None:
    return next(
        (c for c in trip.collaborators if c.clerk_id == user_id and c.status == "active"),
        None,
    )


def _can_write(trip: TripDocument, user_id: str) -> bool:
    if _is_owner(trip, user_id):
        return True
    collab = _get_collab(trip, user_id)
    return collab is not None and collab.role == CollaboratorRole.EDITOR


def _can_read(trip: TripDocument, user_id: str) -> bool:
    if trip.is_public or _is_owner(trip, user_id):
        return True
    return _get_collab(trip, user_id) is not None


# ── Request schemas ──────────────────────────────────────────────────


class InviteBody(BaseModel):
    role: CollaboratorRole = CollaboratorRole.VIEWER
    name: str = "Collaborator"
    email: str | None = None


# ── Endpoints ────────────────────────────────────────────────────────


@router.post("/trips/{trip_id}/invite")
async def create_invite(
    trip_id: str,
    user_id: str = Query(...),
    body: InviteBody = Body(...),
) -> dict:
    """Generate a shareable invite link. Only the trip owner can invite."""
    trip = await TripService.get(trip_id, user_id=user_id)

    pending = TripCollaborator(
        name=body.name,
        email=body.email,
        role=body.role,
        status="pending",
    )
    # invite_token is auto-generated by TripCollaborator default_factory
    trip.collaborators.append(pending)
    trip.updated_at = datetime.now(UTC)
    await trip.save()

    return {
        "ok": True,
        "data": {
            "invite_token": pending.invite_token,
            "invite_url": f"/api/invite/{pending.invite_token}/accept",
            "role": pending.role,
            "collab_id": pending.id,
        },
    }


@router.get("/invite/{token}/accept")
async def accept_invite(
    token: str,
    user_id: str = Query(...),
) -> dict:
    """Accept an invite by token — links the authenticated user to the trip."""
    trip = await TripDocument.find_one({"collaborators": {"$elemMatch": {"invite_token": token}}})
    if not trip:
        raise NotFoundError("Invite", token)

    accepted_role: CollaboratorRole = CollaboratorRole.VIEWER
    for collab in trip.collaborators:
        if collab.invite_token == token:
            if collab.status == "active":
                return {"ok": False, "data": {"message": "Invite already used."}}
            collab.clerk_id = user_id
            collab.status = "active"
            collab.joined_at = datetime.now(UTC)
            accepted_role = collab.role
            break

    trip.updated_at = datetime.now(UTC)
    await trip.save()

    return {
        "ok": True,
        "data": {
            "trip_id": str(trip.id),
            "trip_title": trip.title,
            "role": accepted_role,
        },
    }


@router.get("/trips/{trip_id}/collaborators")
async def list_collaborators(
    trip_id: str,
    user_id: str = Query(...),
) -> dict:
    """List active collaborators (excludes pending invites)."""
    trip = await TripService.get(trip_id, user_id=user_id)

    active = [c for c in trip.collaborators if c.status == "active"]
    pending_count = sum(1 for c in trip.collaborators if c.status == "pending")

    return {
        "ok": True,
        "data": {
            "owner": trip.user_id,
            "collaborators": [
                {
                    "id": c.id,
                    "clerk_id": c.clerk_id,
                    "name": c.name,
                    "role": c.role,
                    "joined_at": c.joined_at.isoformat() if c.joined_at else None,
                }
                for c in active
            ],
            "pending_count": pending_count,
        },
    }


@router.patch("/trips/{trip_id}/collaborators/{collab_id}/role")
async def update_collaborator_role(
    trip_id: str,
    collab_id: str,
    user_id: str = Query(...),
    role: CollaboratorRole = Query(...),
) -> dict:
    """Change a collaborator's role. Owner only."""
    trip = await TripService.get(trip_id, user_id=user_id)

    for collab in trip.collaborators:
        if collab.id == collab_id:
            collab.role = role
            break
    else:
        raise NotFoundError("Collaborator", collab_id)

    trip.updated_at = datetime.now(UTC)
    await trip.save()
    return {"ok": True, "data": {"collab_id": collab_id, "role": role}}


@router.delete("/trips/{trip_id}/collaborators/{collab_id}")
async def remove_collaborator(
    trip_id: str,
    collab_id: str,
    user_id: str = Query(...),
) -> dict:
    """Remove a collaborator. Owner can remove anyone; members can remove themselves."""
    trip = await TripService.get(trip_id, user_id=user_id)

    target = next((c for c in trip.collaborators if c.id == collab_id), None)
    if not target:
        raise NotFoundError("Collaborator", collab_id)

    if not _is_owner(trip, user_id) and target.clerk_id != user_id:
        return {"ok": False, "data": {"message": "Only the owner can remove others."}}

    trip.collaborators = [c for c in trip.collaborators if c.id != collab_id]
    trip.updated_at = datetime.now(UTC)
    await trip.save()
    return {"ok": True, "data": None}


@router.get("/trips/{trip_id}/can-edit")
async def check_edit_permission(
    trip_id: str,
    user_id: str = Query(...),
) -> dict:
    """Quick permission check — used by frontend before showing edit UI."""
    trip = await TripDocument.get(trip_id)
    if not trip:
        raise NotFoundError("Trip", trip_id)

    return {
        "ok": True,
        "data": {
            "can_read": _can_read(trip, user_id),
            "can_write": _can_write(trip, user_id),
            "is_owner": _is_owner(trip, user_id),
        },
    }
