"""W20 — Trip book layout generator.

Builds a structured JSON layout for a printable travel book.
The layout is consumed by the web print CTA and can be sent to
print-on-demand APIs (Lulu, Blurb, Printful) for fulfilment.

In production, swap _render_pdf_stub() for a real PDF renderer
(WeasyPrint, ReportLab, or a headless Chrome screenshot pipeline).
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime

logger = logging.getLogger(__name__)


def _fmt_date(dt: datetime | None) -> str:
    if not dt:
        return ""
    return dt.strftime("%B %d, %Y")


def build_book_layout(trip) -> dict:  # trip: TripDocument
    """Return a structured book layout dict.

    Structure:
      title_page, introduction, day_pages[], map_page, credits
    Each page has: type, title, body, pins (for day pages).
    """
    ordered_pins = sorted(trip.pins, key=lambda p: p.order)
    visited = [p for p in ordered_pins if p.visited_at]

    # Group pins by itinerary day (if itinerary exists) or sequential chunks
    days: list[dict] = []
    if trip.itinerary:
        for day in sorted(trip.itinerary, key=lambda d: d.day_number):
            day_pins = [p for p in ordered_pins if p.id in set(day.pin_ids)]
            days.append(
                {
                    "day_number": day.day_number,
                    "label": day.label or f"Day {day.day_number}",
                    "notes": day.notes,
                    "pins": [_pin_dict(p) for p in day_pins],
                }
            )
    else:
        # No itinerary — split into chunks of 5 stops per "day"
        chunk = 5
        for i in range(0, len(ordered_pins), chunk):
            slice_pins = ordered_pins[i : i + chunk]
            days.append(
                {
                    "day_number": i // chunk + 1,
                    "label": f"Day {i // chunk + 1}",
                    "notes": None,
                    "pins": [_pin_dict(p) for p in slice_pins],
                }
            )

    layout = {
        "generated_at": datetime.now(UTC).isoformat(),
        "title": trip.title,
        "pages": [
            # ── Title page
            {
                "type": "title",
                "title": trip.title,
                "body": f"A travel guide inspired by a {trip.platform or 'video'} journey.",
                "stop_count": len(ordered_pins),
                "visited_count": len(visited),
            },
            # ── Introduction
            {
                "type": "introduction",
                "title": "About This Trip",
                "body": (
                    f"This book was generated from {len(ordered_pins)} stops "
                    f"discovered in a travel video"
                    + (f" by {trip.video_creator}" if trip.video_creator else "")
                    + ". Each page highlights a destination with context pulled "
                    "directly from the video."
                ),
            },
            # ── One page per day
            *[
                {
                    "type": "day",
                    "day_number": day["day_number"],
                    "title": day["label"],
                    "notes": day["notes"],
                    "pins": day["pins"],
                }
                for day in days
            ],
            # ── Map overview
            {
                "type": "map",
                "title": "Full Route Overview",
                "body": "All stops plotted in visit order.",
                "pins": [_pin_dict(p) for p in ordered_pins],
            },
            # ── Credits
            {
                "type": "credits",
                "title": "Credits",
                "body": (
                    "Generated by ReelRoutes — AI-powered travel planning from real videos. "
                    "reelroutes.app"
                ),
                "source_url": trip.source_url,
                "video_creator": trip.video_creator,
            },
        ],
        "page_count": 3 + len(days),  # title + intro + days + map + credits
        "print_specs": {
            "format": "6x9",
            "units": "inches",
            "color": "full_color",
            "paper": "matte",
            "suggested_vendor": "Lulu",
            "vendor_api_docs": "https://developers.lulu.com/products-reference",
        },
    }
    return layout


def _pin_dict(pin) -> dict:
    return {
        "id": pin.id,
        "name": pin.place_name,
        "lat": pin.lat,
        "lng": pin.lng,
        "address": pin.address,
        "context_quote": pin.context_quote,
        "rating": pin.rating,
        "website": pin.website,
        "category": pin.category if hasattr(pin, "category") else None,
        "visited": pin.visited_at is not None,
        "diary_entry": pin.diary_entry,
    }
